apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-healthcheck-config
  labels:
    app: nginx
data:
  default.conf: |
    server {
      listen 80;
      
      # Liveness Probe Endpoint
      location /healthz {
        return 200 'OK';
      }
      
      # Readiness Probe Endpoint
      location /readiness {
        return 200 'OK';
      }
      
      # 默认页面
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
