apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: upf-edge-1-1
  namespace: upf-slice4-instance
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|upf-example|upf-example'
spec:
  provider: upf.free5gc.io

  # 这里只保留 CRD 允许的字段：name / ipv4 / ipv6 / vlanID
  interfaces:
  - name: n4
  - name: n3
  - name: n6

  # 用 networkInstances 来绑定“哪个 network instance 包含哪些接口”
  networkInstances:
  - name: n4
    interfaces: ["n4"]
  - name: n3
    interfaces: ["n3"]
  - name: n6
    interfaces: ["n6"]
