apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: upf-slice4-instance/upf-edge-1-1
  name: upf-edge-1-1-1-1-1-1-1
  namespace: upf-slice1-instance
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|upf-slice4-instance|upf-edge-1-1'
spec:
  provider: upf.free5gc.io
